### ISSUE TITLE
Writing non-interleaved disk image files doesn't work

### ISSUE THREAD

**Issue by sneakywumpus** [ogdenpm/disktools#2]
It still applies an interleave of 1. After making the changes below I could successfully generate disk images for the Intel MDS-800 emulator I'm currently writing for [z80pack](https://github.com/udo-munk/z80pack/tree/dev).

```
diff --git a/mkidsk/writeImage.c b/mkidsk/writeImage.c
index 81befc1..f987fc2 100644
--- a/mkidsk/writeImage.c
+++ b/mkidsk/writeImage.c
@@ -95,12 +95,12 @@ void WriteImgFile(char *fname, int diskType, char *interleaves, bool useSkew, ch
     
     int skew = interleaves && useSkew ? formats[diskType].skew : -1;
     char *modeSize = formats[diskType].modeSize;
-    int interleave = 1;
+    int interleave = 0;
     int mode = 0;
     int sSize = 0;
 
     if (!interleaves) {
-        interleaves = "1";
+        interleaves = "";
     } else if (!*interleaves)
         interleaves = formats[diskType].tInterLeave;
 
```

**Comment by ogdenpm** [comment]
You can force interleave using the -i option and intertrack skew with -t,  however I query why you are applying interleave or skew to an image file.

The main reason for interleave is to optimise the read of the next sector. There are two basic approaches to this

1. The OS provides a logical track/sector (e.g. CP/M) and the sector is mapped to a real physical sector on the disk. In this case the physical sectors are typically written with consecutive sector numbers.  As an example logical sector may be mapped to physical sector 4. In tools that write CP/M disks you might need to apply interleave to the image file to account for this mapping, or have an inverse mapping function in your disk emulator.

2. The OS provides a physical track/sector (e.g. ISIS) so there is no translation of the sector. Instead, the interleave is only used at format time to lay out the physical sector IDs on the disk. After format, the OS doesn't care about the interleave, it just requests a physical sector. This is why for a .img file I would not recommend interleave for an ISIS disk, so that the sector can be accessed simply. For .imd which may be written to a physical disk, the interleave should be present to ensure that the physical sectors are written correctly.

Note, for true ISIS disks, the interleave is different for tracks 0, 1 and for the rest of the disk there is an intertrack skew to allow for head settle time., which would further scramble an .img file if the interleave was applied.

**Comment by ogdenpm** [comment]
Forgot to note, see https://mark-ogden.uk/idkstool.html , which has a diagram showing the layout of sectors.

Also my CP/M example of mapping I accidentally missed some information.

Assuming an interleave of 3 then for CP/M and sector ids 1 2 3 4 ....
logical sector 1 -> physical sector 1
logical sector 2 -> physical sector 4
logical sector 3 -> physical sector 7
...
For ISIS the sector id's would be laid out in the order (inter track skew not shown)
1 ? ? 2 ? ? 3 where ? would be other sector id's depending on the sectors per track.

**Comment by sneakywumpus** [comment]
I don't want interleaved image files.

I started with disk images from Bill Beech's site, which work fine on my simulator, but then I found your ISIS repository, and tried to create an image, e.g.

`mkidsk "recipes/@II-970003-08-DB ISIS-II Operating System V4.3" os.img`

(I ported `mkidsk`, `unidsk`, and `irepo` to Linux. The changes are a bit quick & dirty, tell me if you want them).

The file produced is interleaved (which should only be the case if using `-i` according to [this](https://mark-ogden.uk/idkstool.html)) and doesn't work with my emulator.

I then started to look at the source code for `mkidsk`, and found that `WriteImgFile` gets passed a `NULL` for `interleaves` when `-i` is not specified. This causes `interleaves`  to be set to `"1"` later, which then leads to `interleave` to be set to `1` which gets passed to `BuildSMap`.

With my changes `interleave` is left at `0` when `interleaves` is `NULL` and a non-interleaved image file is produced.

The file produced by the `mkidsk` example above is now identical (except for the unused bytes) to [this](https://www.nj7p.info/Disk%20Images/7Z/9700003-08_Diskette_Operating_System_V4.3_DD.7z) and works in my emulator.

Thank you for your incredible work on the ISIS repository,

Thomas Eberhardt

**Comment by ogdenpm** [comment]
After further looking at the code, the issue was that I applied an initial interleave before assigning the first slot. For .img files this lead to a blank  first sector. The change was to treat interleave to be handled similar to iPDS files which don't have an initial interleave applied, unlike ISIS disks. Note skew is still used if specified.
I also modified the code to build cleanly under Linux using GCC and added a suitable make file in the Linux directory. 
I also took the opportunity to update the mkidsk tool to use my latest version model.

**Comment by sneakywumpus** [comment]
Thanks. I can now build bootable images on Linux but needed to convert the recipe files from CRLF to LF line endings,
otherwise one gets an error message like:
```
./mkidsk recipes/@II-970003-08-DB\ ISIS-II\ Operating\ System\ V4.3  x.img
Unsupported disk format ISIS II DD
```
 which doesn't really point to the underlying problem.

**Comment by ogdenpm** [comment]
I have modified mkidsk to ingore '\r' so you can now use the windows recipes. I have also decided to ignore interleave and skew for .img files as they make no sense.
I have also modified unidsk to build under Linux.
I have tested producing a disk using mkidsk and extracted the files using unidsk, both on windows and Linux

**Comment by sneakywumpus** [comment]
Did you forget to push the updated code, or is it not yet ready?

I'll close the issue, since the problem is fixed. Thanks again.
